Update the pre-push GitHub hook

diff --git a/src/test/scripts/git-hooks/pre-push b/src/test/scripts/git-hooks/pre-push
--- a/src/test/scripts/git-hooks/pre-push
+++ b/src/test/scripts/git-hooks/pre-push
@@ -2,11 +2,11 @@
 
 # Prevent pushes that would cause the CI build to fail.
 
-mvn clean install
+mvn clean verify
 
 if [ $? -ne 0 ]
 then
-    echo >&2 "\nThe build command 'mvn clean install' failed, not pushing"
+    echo >&2 "\nThe build command 'mvn clean verify' failed, not pushing"
     exit 1
 fi
 
